name: Compile and Publish

on:
  push:
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Compile title page
        uses: xu-cheng/latex-action@v4
        with:
          root_file: front.tex
          working_directory: ./titlepage

      - name: Compile main document
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex

      - name: Compile slides
        uses: xu-cheng/latex-action@v4
        with:
          root_file: main.tex
          working_directory: ./slides

      - name: Install pdftk
        run: sudo apt-get update && sudo apt-get install -y pdftk-java

      - name: Prepare Public Folder
        run: |
          mkdir -p public
          pdftk titlepage/front.pdf main.pdf cat output public/thesis.pdf
          cp slides/main.pdf public/presentation-slides.pdf

      - name: Generate Directory Index
        uses: gacts/directory-listing@v1
        with:
          target: ./public

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4

